# Generated by Django 5.1.3 on 2025-05-09 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_points', models.IntegerField(default=0)),
                ('rationality_score', models.IntegerField(default=0)),
                ('decisiveness_score', models.IntegerField(default=0)),
                ('empathy_score', models.IntegerField(default=0)),
                ('clarity_score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('daily_streak', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
