# Generated by Django 5.1.3 on 2025-05-09 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_is_premium_dailychallenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='unlocked_at_level',
            field=models.IntegerField(default=1, help_text='Minimum level required to unlock this scenario'),
        ),
        migrations.AddField(
            model_name='scenariooption',
            name='next_scenario',
            field=models.ForeignKey(blank=True, help_text='Next scenario to show based on this option', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_options', to='core.scenario'),
        ),
        migrations.AddField(
            model_name='userscenarioprogress',
            name='attempts',
            field=models.IntegerField(default=0, help_text='Number of times the user has attempted this scenario'),
        ),
        migrations.AddField(
            model_name='userscenarioprogress',
            name='last_attempt_date',
            field=models.DateField(blank=True, help_text='Date of the last attempt', null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='category',
            field=models.CharField(choices=[('career', 'Career Decisions'), ('finance', 'Financial Decisions'), ('relationships', 'Relationship Decisions'), ('time_management', 'Time Management'), ('education', 'Educational Decisions'), ('health', 'Health & Wellness'), ('ethics', 'Ethics'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='DailyUsageTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('scenarios_generated', models.IntegerField(default=0, help_text='Number of scenarios generated today')),
                ('scenarios_attempted', models.IntegerField(default=0, help_text='Number of scenarios attempted today')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
