# Generated by Django 5.1.3 on 2025-05-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scenario_unlocked_at_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('career_coach', 'Career Coach'), ('financial_advisor', 'Financial Advisor'), ('relationship_counselor', 'Relationship Counselor'), ('time_management_expert', 'Time Management Expert'), ('educational_consultant', 'Educational Consultant'), ('health_wellness_coach', 'Health & Wellness Coach'), ('life_coach', 'Life Coach')], max_length=50)),
                ('description', models.TextField()),
                ('expertise', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mentor_images/')),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
