# Generated by Django 5.1.3 on 2025-05-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mentor_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='type',
            field=models.CharField(choices=[('career_coach', 'Career Coach'), ('financial_advisor', 'Financial Advisor'), ('relationship_counselor', 'Relationship Counselor'), ('time_management_expert', 'Time Management Expert'), ('educational_consultant', 'Educational Consultant'), ('health_wellness_coach', 'Health & Wellness Coach'), ('life_coach', 'Life Coach'), ('astrology_expert', 'Astrology Expert'), ('creative_thinking_coach', 'Creative Thinking Coach')], max_length=50),
        ),
    ]
