# Generated by Django 5.1.3 on 2025-05-09 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mentorchat_mentorchatusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-friendly identifier (e.g., 'mbti', 'genz-vs-millennial')", unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Main description of the test')),
                ('icon', models.CharField(choices=[('Brain', 'Brain'), ('Sparkles', 'Sparkles'), ('Workflow', 'Workflow'), ('Lightbulb', 'Lightbulb'), ('Heart', 'Heart'), ('TrendingUp', 'TrendingUp')], default='Brain', max_length=20)),
                ('question_count', models.IntegerField(default=0, help_text='Number of questions in the test')),
                ('time_to_complete', models.CharField(blank=True, help_text="Estimated time to complete (e.g., '5 minutes')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='personality_test_images/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PersonalityTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('order', models.IntegerField(default=0, help_text='Order in which questions appear')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.personalitytest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PersonalityTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personalitytestquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='test_result_images/')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.personalitytest')),
            ],
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(blank=True, help_text='JSON containing answers and scores', null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personalitytestresult')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personalitytest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
