# Generated by Django 5.1.3 on 2025-05-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_personalitytest_personalitytestquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='decision_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mbti_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_bias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
