# Generated by Django 5.1.3 on 2025-05-10 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_rank_profile_total_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time the user was active on the site'),
        ),
    ]
