# Generated by Django 5.1.3 on 2025-05-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_userquestionresponse_selected_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('post', 'Post'), ('comment', 'Comment'), ('join_group', 'Join Group'), ('like', 'Like'), ('message', 'Message'), ('chat', 'Chat'), ('scenario', 'Scenario'), ('assessment', 'Assessment'), ('level_up', 'Level Up'), ('support_issue', 'Support Issue'), ('issue_comment', 'Issue Comment'), ('ran_add_fake_users', 'Generated Fake Users'), ('ran_add_mentors', 'Added Default Mentors'), ('ran_add_test_scenarios', 'Generated Test Scenarios'), ('ran_add_personality_tests', 'Added Default Personality Tests'), ('ran_add_user_progress', 'Added User Progress'), ('ran_setup_demo_data', 'Setup All Demo Data'), ('database_backup', 'Database Backup'), ('clear_cache', 'Cleared Cache'), ('set_user_premium', 'Set User Premium'), ('set_user_free', 'Set User Free')], max_length=30),
        ),
    ]
