# Generated by Django 5.1.3 on 2025-05-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_create_default_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalitytest',
            name='unlocked_at_level',
            field=models.IntegerField(default=0, help_text='Minimum level required to unlock this test'),
        ),
    ]
