# Generated by Django 5.1.3 on 2025-05-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_personalitytest_unlocked_at_level'),
        ('core', '0021_create_default_superuser'),
    ]

    operations = [
    ]
