# Generated by Django 5.1.3 on 2025-05-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_issue_type_to_supportissue'),
        ('core', '0023_merge_20250512_2205'),
    ]

    operations = [
    ]
