# Generated by Django 5.1.3 on 2025-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_increase_field_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitytest',
            name='unlocked_at_level',
            field=models.IntegerField(default=1, help_text='Minimum level required to unlock this test'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='decision_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_bias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
