# Generated by Django 5.1.3 on 2025-05-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_notification'),
    ]

    operations = [
    ]
