# Generated by Django 5.1.3 on 2025-05-28 17:57

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_communitymessage_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='communitymessage',
            name='core_commun_sender__27733e_idx',
        ),
        migrations.RemoveIndex(
            model_name='directmessage',
            name='core_direct_sender__cf239d_idx',
        ),
        migrations.RemoveIndex(
            model_name='directmessage',
            name='core_direct_recipie_1cdcee_idx',
        ),
        migrations.AlterField(
            model_name='communitymessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='date_created',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_expires',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userscenarioprogress',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userscenarioprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userscenarioprogress',
            name='last_attempt_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date of the last attempt', null=True),
        ),
        migrations.AddIndex(
            model_name='dailychallenge',
            index=models.Index(fields=['user', 'date_created'], name='core_dailyc_user_id_ea9fee_idx'),
        ),
        migrations.AddIndex(
            model_name='dailychallenge',
            index=models.Index(fields=['user', 'completed'], name='core_dailyc_user_id_4f7b55_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='core_notifi_notific_cbfe88_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['level'], name='core_profil_level_791d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['xp_points'], name='core_profil_xp_poin_4ee73e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['last_activity'], name='core_profil_last_ac_9339b7_idx'),
        ),
        migrations.AddIndex(
            model_name='userscenarioprogress',
            index=models.Index(fields=['user', 'completed'], name='core_usersc_user_id_1dba87_idx'),
        ),
        migrations.AddIndex(
            model_name='userscenarioprogress',
            index=models.Index(fields=['completed_at'], name='core_usersc_complet_17f90e_idx'),
        ),
    ]
