# Generated by Django 4.2.11 on 2025-05-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.CharField(blank=True, help_text='Path to image file in static/img/mentor_images/ directory', max_length=255, null=True),
        ),
    ]
